### ISSUE TITLE
Splash screen UX subtles

### ISSUE THREAD

**Issue by molostoff** [newenclave/AtomAppGN#6]
Please, remove splashcreen startup and also re-selecting last used device that already selected, to make faster access to the application itself, since pressing too much buttons is incredibly time expensive on the go.

**Comment by newenclave** [comment]
Version 0.3.4 
Added an option to enable/disable the splash screen. Also you can double press to "Start" button (upper right) to run "last used" or "scan" if it was impossible to save any last device used. Some devices do not sopport this feature

PS: The version is in app store, but should be approved. ETA 2h+
