### ISSUE TITLE
Garmin Enduro support

### ISSUE THREAD

**Issue by msiuka** [newenclave/AtomAppGN#7]
Have a Atom device, Garmin Enduro watch and Garmin Edge 1000 device. There were thoughts about connecting Atom device to my garmins. Now find this project and may be you (or me if i found time) add support for more garmin devices.

**Comment by newenclave** [comment]
Version 0.3.4 
Added Enduro support.
 Unfortunately it's impossible to add "Edge 1000" It doesn't support APIs needed.  

PS: Version is in the app store but should be approved.
